name: advent_of_code_2024
description: My attempt to completge the Advent of Code 2024.
version: 1.0.0
repository: https://github.com/ChuyEx/AdventOfCode2024

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
